"""Migration commit: f58bcb13-7bd4-43e6-ba97-b3f73231e8ea

Revision ID: 749788d22034
Revises: 1323ad0a0c7d
Create Date: 2025-02-12 09:52:17.310403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749788d22034'
down_revision = '1323ad0a0c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
